---
- name: Remove IP Connectivity for L3 Fabric
  hosts: switches
  connection: local
  tasks:
    - name: Remove IPv4 Address on Interface
      loop_control:
        pause: 1
      with_items: "{{ l3_fabric.interfaces }}"
      nxos_ip_interface:
        provider: "{{ provider }}"
        state: absent
        interface: "{{ item.name }}"
    - name: Reset Interface Configuration
      loop_control:
        pause: 1
      with_items: "{{ l3_fabric.interfaces }}"
      nxos_interface:
        provider: "{{ provider }}"
        interface: "{{ item.name }}"
        mode: layer3
        description: "{{ item.name }}"
        admin_state: up
