---
- name: Disable OSPF Feature
  hosts: switches
  connection: local
  tasks:
    - name: Disable OSPF Feature
      nxos_feature:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        feature: ospf
        state: disabled
