---

- name: ENSURE THAT THE TFTP SERVER IS INSTALLED
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - xinetd
    - tftp-server
    - tftp

- name: ENSURE THAT THE TFTP CONFIGS ARE INSTALLED
  copy:
    src: files/tftp
    dest: /etc/xinetd.d/tftp
  notify: start tftp

- name: ENSURE THE SERVICE IS STARTED
  systemd:
    name: tftp
    state: started
    enabled: yes
