provider:
  host: "{{ inventory_hostname }}"
  transport: cli
  use_ssl: yes
  validate_certs: no
  timeout: 20

vlans:
  - vlan_id: 10
    name: Network10
    interface: Vlan10
    prefix: 10.30.1.
    gw_mask: 24
    gw_addr: 10.30.1.1

ospf:
  process: 0
  area: 0

hsrp:
  group: 10
